services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    expose:
      - "8096"
    labels:
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.tjarksievers.de`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=certresolver"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - jellyfin_media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.tjarksievers.de
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - reverse-proxy
    networks:
      - reverse-proxy


volumes:
  jellyfin_config:
  jellyfin_cache:
  jellyfin_media: