services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    expose:
      - "8000"
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    labels:
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.tjarksievers.de`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=certresolver"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - jellyfin_media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.tjarksievers.de
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'


volumes:
  jellyfin_config:
  jellyfin_cache:
  jellyfin_media: