services:
  usa-tjarksievers-de:
    image: wordpress
    restart: always
    container_name: usa-tjarksievers-de
    labels:
      - "traefik.http.routers.usa-tjarksievers-de.rule=Host(`usa.tjarksievers.de`)"
      - "traefik.http.routers.usa-tjarksievers-de.tls=true"
      - "traefik.http.routers.usa-tjarksievers-de.tls.certresolver=certresolver"
      - "traefik.http.routers.usa-tjarksievers-de.middlewares=compress, cache-header"
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.middlewares.cache-header.headers.customresponseheaders.Cache-Control=max-age=31536000"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress-db
    volumes:
      - wordpress:/var/www/html
    networks:
      - reverse-proxy
    depends_on:
      - reverse-proxy

  usa-tjarksievers-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - usa-tjarksievers-db:/var/lib/mysql

volumes:
  wordpress:
  usa-tjarksievers-db: